package com.dpdms.dashboard;
import org.springframework.beans.factory.ObjectProvider;import org.springframework.beans.factory.annotation.Value;import org.springframework.boot.SpringApplication;import org.springframework.boot.autoconfigure.SpringBootApplication;import org.springframework.cloud.client.ServiceInstance;import org.springframework.cloud.client.discovery.DiscoveryClient;import org.springframework.core.ParameterizedTypeReference;import org.springframework.http.*;import org.springframework.stereotype.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.client.RestClient;
import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;import java.util.stream.*;
@SpringBootApplication public class DashboardServiceApplication{public static void main(String[]args){SpringApplication.run(DashboardServiceApplication.class,args);}}
@Component class DashboardAggregator{
    private final ObjectProvider<DiscoveryClient>provider;private final RestClient.Builder builder;private final String secret;
    DashboardAggregator(ObjectProvider<DiscoveryClient>provider,RestClient.Builder builder,@Value("${dpdms.gateway-secret}")String secret){this.provider=provider;this.builder=builder;this.secret=secret;}
    List<Map<String,Object>> approved(String service,Map<String,String>headers){DiscoveryClient d=provider.getIfAvailable();if(d==null)return List.of();List<ServiceInstance>xs=d.getInstances(service);if(xs.isEmpty())return List.of();String path=switch(service){case "FLOOD-SERVICE"->"/api/v1/floods/approved";case "DROUGHT-SERVICE"->"/api/v1/droughts/approved";case "FIRE-SERVICE"->"/api/v1/fires/approved";case "ZOONOTIC-SERVICE"->"/api/v1/zoonotic/approved";default->"/api/v1/mining-accidents/approved";};HttpHeaders h=new HttpHeaders();h.set("X-Gateway-Secret",secret);headers.forEach(h::set);ResponseEntity<List<Map<String,Object>>>r=builder.build().get().uri(xs.get(0).getUri()+path).headers(x->x.addAll(h)).retrieve().toEntity(new ParameterizedTypeReference<List<Map<String,Object>>>(){});return r.getBody()==null?List.of():r.getBody();}
}
@RestController @RequestMapping("/api/v1/dashboard") class DashboardController{
    private final DashboardAggregator aggregator;private final String gatewaySecret;DashboardController(DashboardAggregator aggregator,@Value("${dpdms.gateway-secret}")String gatewaySecret){this.aggregator=aggregator;this.gatewaySecret=gatewaySecret;}
    @GetMapping("/summary") Map<String,Object>summary(@RequestHeader("X-Gateway-Secret")String gatewayHeader,@RequestHeader("X-User-Role")String role,@RequestHeader("X-User-Hazard")String uh,@RequestHeader("X-User-Username")String user,@RequestHeader(value="X-User-Ward",required=false)String ward,@RequestHeader(value="X-User-District",required=false)String district,@RequestHeader(value="X-User-Province",required=false)String province){
        if(!Objects.equals(gatewayHeader,gatewaySecret))throw new DashboardForbiddenException("Forbidden");
        Map<String,String>headers=Map.of("X-User-Role",role,"X-User-Hazard",uh,"X-User-Username",user,"X-User-Ward",Objects.toString(ward,""),"X-User-District",Objects.toString(district,""),"X-User-Province",Objects.toString(province,""));
        List<Map<String,Object>>all=new ArrayList<>();List<String>unavailable=new ArrayList<>();
        for(String service:List.of("FLOOD-SERVICE","DROUGHT-SERVICE","FIRE-SERVICE","ZOONOTIC-SERVICE","MINING-SERVICE")){try{for(Map<String,Object>m:aggregator.approved(service,headers)){Map<String,Object>x=new LinkedHashMap<>(m);x.put("hazard",service.replace("-SERVICE",""));all.add(x);}}catch(Exception e){unavailable.add(service);}}
        Map<String,Long>byHazard=all.stream().collect(Collectors.groupingBy(m->Objects.toString(m.get("hazard")),TreeMap::new,Collectors.counting()));
        Map<String,Long>bySeverity=all.stream().collect(Collectors.groupingBy(m->Objects.toString(m.get("severity")),TreeMap::new,Collectors.counting()));
        Map<String,Long>byStatus=all.stream().collect(Collectors.groupingBy(m->Objects.toString(m.get("status")),TreeMap::new,Collectors.counting()));
        List<Map<String,Object>>recent=all.stream().sorted(Comparator.comparing(m->Objects.toString(m.get("occurrenceAt")),Comparator.reverseOrder())).limit(10).toList();
        Map<String,Long>trend=all.stream().filter(m->m.get("occurrenceAt")!=null).collect(Collectors.groupingBy(m->{try{return LocalDateTime.parse(Objects.toString(m.get("occurrenceAt"))).toLocalDate().toString();}catch(Exception e){return "UNKNOWN";}},TreeMap::new,Collectors.counting()));
        List<Map<String,Object>>mapIncidents=all.stream().filter(m->m.get("latitude")!=null&&m.get("longitude")!=null).map(m->{Map<String,Object>x=new LinkedHashMap<>();x.put("id",m.get("id"));x.put("hazard",m.get("hazard"));x.put("ward",m.get("ward"));x.put("severity",m.get("severity"));x.put("occurrenceAt",m.get("occurrenceAt"));x.put("latitude",m.get("latitude"));x.put("longitude",m.get("longitude"));return x;}).toList();
        return Map.of("totalApproved",all.size(),"countsByHazard",byHazard,"countsBySeverity",bySeverity,"countsByStatus",byStatus,"recentIncidents",recent,"trend",trend,"mapIncidents",mapIncidents,"unavailableHazards",unavailable,"lastRefresh",LocalDateTime.now());
    }
    @GetMapping("/incidents") List<Map<String,Object>>incidents(@RequestHeader("X-Gateway-Secret")String gatewayHeader,@RequestHeader("X-User-Role")String role,@RequestHeader("X-User-Hazard")String uh,@RequestHeader("X-User-Username")String user,@RequestHeader(value="X-User-Ward",required=false)String ward,@RequestHeader(value="X-User-District",required=false)String district,@RequestHeader(value="X-User-Province",required=false)String province){return (List<Map<String,Object>>)summary(gatewayHeader,role,uh,user,ward,district,province).get("mapIncidents");}
}
class DashboardForbiddenException extends RuntimeException { DashboardForbiddenException(String message){super(message);} }
@RestControllerAdvice class DashboardErrors { @ExceptionHandler(DashboardForbiddenException.class) ResponseEntity<?> forbidden(DashboardForbiddenException e){return ResponseEntity.status(403).body(Map.of("error","FORBIDDEN","message",e.getMessage()));} }

