CREATE DATABASE IF NOT EXISTS dpdms_auth;
CREATE DATABASE IF NOT EXISTS dpdms_flood;
CREATE DATABASE IF NOT EXISTS dpdms_drought;
CREATE DATABASE IF NOT EXISTS dpdms_fire;
CREATE DATABASE IF NOT EXISTS dpdms_zoonotic;
CREATE DATABASE IF NOT EXISTS dpdms_mining;
CREATE DATABASE IF NOT EXISTS dpdms_alerts;
GRANT ALL PRIVILEGES ON dpdms_%.* TO 'dpdms'@'%';
FLUSH PRIVILEGES;
